language: python
python:
  - "3.6"
env:
  - NODE_VERSION="8"

cache:
  pip: true
  directories:
    - ./node_modules

before_install:
  - nvm --version
  - nvm install $NODE_VERSION
  - node --version
  - npm --version

install:
  - pip install awscli
  - npm install

script:
  # Ideally this would be "npm run test" to get the e2e tests too
  # They don't Just Work, haven't debugged getting them to play nice on travis yet
  - npm run unit
  - npm run build

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.seattlehumanekennelhub.org
  skip_cleanup: true
  region: us-west-2
  local_dir: dist

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"